### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by lUjek-Sh** [Samuel-Unknown/Gallery-Image-Picker#17]
Hi. Please release disable or enable multi select

**Comment by Samuel-Unknown** [comment]
Hi, I will add this feature in the next release

**Comment by lUjek-Sh** [comment]
> Hi, I will add this feature in the next release

Is the library dead?

**Comment by Samuel-Unknown** [comment]
I have implemented a single selection mode in a new [release v1.4.0](https://github.com/Samuel-Unknown/Gallery-Image-Picker/releases/tag/v1.4.0). Thank you for waiting! 😊
